sudo: required
dist: trusty

before_install:
  - easy_install --version
  - pip freeze
  - travis_retry pip install -U setuptools

script:
  - bash -xve ./test/travis_ros_install.bash
#  - source ~/catkin_ws/devel/setup.bash
#  - bash -xve ./test/travis_package_make.bash


