sudo: required
dist: trusty

before_install:
  - "easy_install --version"
  - "pip freeze"
  - "pip install --upgrade pip"

script:
  - bash -xve ./test/travis_ros_install.bash
#  - source ~/catkin_ws/devel/setup.bash
#  - bash -xve ./test/travis_package_make.bash


